### ISSUE TITLE
ghdl analyze options missing in --elab-run command

### ISSUE THREAD

**Issue by ThomasHornschuh** [olofk/edalize#11]
The --elab-run command of ghdl requires the analyze-options to work correctly. So line 54 in ghdl.py should  be changed to
`ghdl --elab-run  $(ANALYZE_OPTIONS) $(STD) $(TOPLEVEL) $(RUN_OPTIONS) $(EXTRA_OPTIONS)`

I think I reported this already a while ago to fusesoc, but not sure anymore, maybe I only intended to report it but never did.

**Comment by olofk** [comment]
Sorry about this. Yes, you reported this in September last year. It's just me being slow. But it's fixed now. Thanks for reporting

**Comment by ThomasHornschuh** [comment]
Great! Thanks.
