### ISSUE TITLE
Vivado's exit status doesn't reflect synthesis result

### ISSUE THREAD

**Issue by a-gibson** [olofk/edalize#121]
I've been trying to automate Vivado synthesis builds into my CI flow and noticed that Vivado returns with status `0` so long as synthesis ran, regardless of result.

From my perspective it is particularly helpful if the exit status reflects the synthesis result because that will allow tools like Jenkins to more easily determine and report accurate results.

I won't have thought over all use cases but I can't think why this would be a bad idea. It would also make behaviour consistent with other tools, such as Quartus.

**Comment by olofk** [comment]
Fixed with #122
