### ISSUE TITLE
VCS backend requires "." (dot) in PATH

### ISSUE THREAD

**Issue by getziadz** [olofk/edalize#14]
The way the Makefile.j2 is written on the VCS backend requires the users to have "." (dot) in their PATH.
```
run: {{ name }}
	{{ name }} -l vcs.log {% for plusarg in plusargs %} {{ plusarg }} {% endfor %}
-----------^
```

**Comment by olofk** [comment]
Thanks! I hope this should be fixed now with 85bfa218e7e889afa329e1aeba70a07aad79b363 Please reopen the issue otherwise
