### ISSUE TITLE
Add include_directory 

### ISSUE THREAD

**Issue by euripedesrocha** [olofk/edalize#142]
Currently all include files are handled tagging is_include_file. Yet in the processing all that happens(as far as I understood it ) is to extract the directory and it to incdirs. The usage of is include file leads to the idea that every include file in the directory should be added to the list, yet this isn´t true.

I would suggest an update to add a include_directory to API and eventually deprecate the is_include_file.

**Comment by olofk** [comment]
Every file used as an include file needs to be marked with `is_include_file : true`. What exactly happens varies a bit between the backends. For most backends this means that the file will be excluded from the list of source files. There is now an option to explicitly set another include directory for a specific include file, but this still requires setting is_include_file. This API will not be deprecated
