### ISSUE TITLE
How to install edalize master alongside Fusesoc

### ISSUE THREAD

**Issue by imuguruza** [olofk/edalize#150]
Hi there,

I want to know how I can use latest `edalize` master with Fusesoc. I have installed it following the instructions and it looks like Fusesoc is calling another version.

Thanks

**Comment by GCHQDeveloper560** [comment]
[Pip's git support](https://pip.pypa.io/en/stable/reference/pip_install/#git) should allow you to install without even having to clone the repo:
```
pip install -U git+https://github.com/olofk/edalize.git@master
```
If you have a local clone then the installation command from the README in that directory should install the checked-out revision to your system/venv.

**Comment by imuguruza** [comment]
Ok thanks!
