### ISSUE TITLE
[Verible] Rename tools

### ISSUE THREAD

**Issue by imphil** [olofk/edalize#167]
Verible (thankfully) renamed their binaries to include "verible" in the name. We need to follow in the verible lint and format backends. 

https://github.com/google/verible/commit/a6d36642f30bacefef405c00ba770b582eb1b2bb

**Comment by olofk** [comment]
I propose we wait until the next stable verible release and then change on the Edalize side.

**Comment by imphil** [comment]
@olofk there hasn't been a stable release of Verible ever, they only provide nightlies with every commit. Given that, and its limited user base, I'd propose to simply rename the tools.

**Comment by olofk** [comment]
Aahh!! What the hell is wrong with all these open source EDA tool developers that just can't take an hour to put out a god damn release. Oh well, I merged the change now, so closing
