### ISSUE TITLE
Revert "silent make" for Verilator

### ISSUE THREAD

**Issue by imphil** [olofk/edalize#20]
After aa30b9e9dcd1c2fa96370f371a1013b805a535d4 Verilator is called with "make -s", suppressing all compiler calls (e.g. `gcc ...`). That makes it *very* hard to debug compiler warnings as we have no idea what options are passed to it. I currently have a failing CI run because of a GCC warning, and just finding out where the "warnings as error" flag is coming from is a pain.

Please revert this commit. Especially in CI we want to have as much information as possible to debug failing runs.

**Comment by olofk** [comment]
I'll revert this for now. Hopefully we will have a better long-term solution where the user can specify the verbosity and get reports on failures
