### ISSUE TITLE
Support synthesis/simulation only Vivado project?

### ISSUE THREAD

**Issue by kele14x** [olofk/edalize#227]
Hi,

Thanks for write this great tool. I'm looking for a proper way to automatic my FPGA design. Usually when design a IP core, I will do synthesis to check the syntax and resource, also will do simulation to dump VCD file to analysis the logic. 

When I try edalize, I found it will automatically run until bitstream generation and try to program hardware board. And sure it will fail, since no .xdc is ready for bitstream generation. 

My question is how to edalize to support synthesis and simulation design flow?

Thanks.

**Comment by imphil** [comment]
How do you run edalize? If you're running FuseSoC, then you can pass it a flag "--setup" to only do the project setup, and if you want, an additional flag "--build" to also build the simulation/synthesis.

**Comment by kele14x** [comment]
hi @imphil 

I'm using bare edalize, and use a python script to add source files, config parameters and run... Maybe I need to look at FuseSOC. Thanks.

**Comment by imphil** [comment]
If you only use edalize you can of course only call the individual steps as well in your Python script. Just choose from `Edatool.configure()`, `Edatool.build()`, `Edatool.run()`. If you only want to produce e.g. project files, call `Edatool.configure()` only.

**Comment by olofk** [comment]
You can get the Vivado backend to only do synthesis by setting `pnr : "none"` in the tool options. This can be done regardless if you're using FuseSoC or Edalize directly

**Comment by olofk** [comment]
@kele14x Are these answers enough to get you going or do you need any more help on this issue?

**Comment by kele14x** [comment]
@olofk sorry for reply late. It's ok for this question. Thanks!
