### ISSUE TITLE
Vivado synt, implementation, bitstream...

### ISSUE THREAD

**Issue by qarlosalberto** [olofk/edalize#246]
Currently icestorm tool in Edalize allow to select ```pnr=none```. It would be a really nice to have a similar option in Vivado. E.g: ```build_step=synt|impl|bitstream```. It's very useful only to run the synthesis to have a resources estimation.

**Comment by olofk** [comment]
`pnr=none` is supported in the Vivado backend already to just run synthesis. There is no option to stop after P&R though, but the bitstream step usually doesn't take too much time

**Comment by qarlosalberto** [comment]
Ohh that option isn't in the documentation: https://edalize.readthedocs.io/en/latest/edam/api.html#vivado
It's really nice, thanks! :)
