### ISSUE TITLE
How to determine the incdir of. V file？

### ISSUE THREAD

**Issue by brodiezhu** [olofk/edalize#253]
How to determine the incdir of. V file？

**Comment by imphil** [comment]
Can you elaborate a bit more on what you're trying to achieve?

**Comment by brodiezhu** [comment]
Source file include other source files, how do we add the path of the include file？















At 2021-07-05 21:28:34, "Philipp Wagner" ***@***.***> wrote:

Can you elaborate a bit more on what you're trying to achieve?

**Comment by imphil** [comment]
If you set `is_include_file` for a file, the path of the file is passed to the simulator or synthesis tool as include path. See https://edalize.readthedocs.io/en/latest/edam/api.html.

**Comment by brodiezhu** [comment]
I have another question, how to set + define + macro = vaule, can you tell me?













At 2021-07-06 16:24:25, "Philipp Wagner" ***@***.***> wrote:

If you set is_include_file for a file, the path of the file is passed to the simulator or synthesis tool as include path. See https://edalize.readthedocs.io/en/latest/edam/api.html.

**Comment by imphil** [comment]
Please again have a look at the API documentation at https://edalize.readthedocs.io/en/latest/edam/api.html#parameter.

**Comment by brodiezhu** [comment]
Thank you very much
















At 2021-07-06 18:55:11, "Philipp Wagner" ***@***.***> wrote:

Please again have a look at the API documentation at https://edalize.readthedocs.io/en/latest/edam/api.html#parameter.

**Comment by brodiezhu** [comment]
I also have a question, if I want to add a new EDA tool to simulate the case, is this behavior feasible?







At 2021-07-06 18:55:11, "Philipp Wagner" ***@***.***> wrote:

Please again have a look at the API documentation at https://edalize.readthedocs.io/en/latest/edam/api.html#parameter.
