### ISSUE TITLE
Is there support for Vivado BD files?

### ISSUE THREAD

**Issue by sjalloq** [olofk/edalize#287]
The Vivado backend seems to have support for XCI IP files but there's no mention of BD files.  Are these just not supported or am I missing something?

**Comment by olofk** [comment]
This is a common question and I'm honestly not sure of the state of this right now. I _think_ some people have gotten it to work but I'm not sure if they needed FuseSoC/Edalize patches or how they did it. I will steer people towards this PR so that we get an idea of the current state

**Comment by sjalloq** [comment]
I'll close this question as I implemented the PR you've seen.

**Comment by olofk** [comment]
For anyone following along, the PR is https://github.com/olofk/edalize/pull/290
