### ISSUE TITLE
Yosys, arch=xilinx fails because of syntax error in write_blif command

### ISSUE THREAD

**Issue by armleo** [olofk/edalize#320]
https://github.com/olofk/fusesoc/issues/569

Exact line causing this issue: https://github.com/olofk/edalize/blob/1e11a12c6354a02e4d6a03c20e11af95238cc739/edalize/yosys.py#L126

**Comment by olofk** [comment]
I believe this should be fixed with https://github.com/olofk/edalize/pull/332 Please reopen if it's still an issue
