### ISSUE TITLE
How best to fix filelist backend

### ISSUE THREAD

**Issue by shareefj** [olofk/edalize#372]
@olofk Thought I'd open a ticket to discuss what we should do here.  Just as some background info:

- we have the filelist backend: https://github.com/olofk/edalize/blob/main/edalize/filelist.py
- this currently requires a new EDAM key of `top_core` which you don't want to merge

So the question is how can we maintain the current functionality without that key change?  To make this backend useful, at least in the way it was intended, was for the flielist to be placed at the same level of hierarchy as the Core file.  The backend does have an `outpath` tool option that the user can set but aside from using environment variables, I'm not aware of any way get the parent directory of the calling core file.

Any thoughts?  If we can't solve this then I'm happy for the filelist backend to be removed rather than have it broken such that it conflicts with our current usage.  I really don't want to get into a branching mess.

Shareef.

**Comment by shareefj** [comment]
OK, how about the following.  Instead of passing `top_core` in the EDAM dict, allow Fusesoc to expand environment variables and a special `__CORE_PATH__` string.  Perhaps there's a cleaner way of doing the same thing but my knowledge of the Fusesoc internals is limited.

```diff
diff --git a/fusesoc/capi2/core.py b/fusesoc/capi2/core.py
index ce17725..745cded 100644
--- a/fusesoc/capi2/core.py
+++ b/fusesoc/capi2/core.py
@@ -79,6 +79,21 @@ class String(str):
         )
 
 
+class StringWithVars(str):
+    """A string containing environment variables to expand and/or the special
+    __CORE_PATH__ variable that should be expanded to the dirname of the parent
+    core file. """
+    
+    def __init__(self, string):
+        self.string = os.path.expandvars(string)
+
+    def parse(self, core_root):
+        self.string = self.string.replace('__CORE_PATH__', core_root)
+
+    def __str__(self):
+        return self.string
+
+
 class Integer(int):
     pass
 
@@ -396,6 +411,8 @@ class Core:
                 if hasattr(section, member):
                     _member = getattr(section, member)
                     if _member:
+                        if isinstance(_member, StringWithVars):
+                            _member.parse(os.path.abspath(self.core_root))
                         options[member] = StringWithUseFlags(_member).parse(flags)
             for member in section.lists:
                 if hasattr(section, member):
```

**Comment by olofk** [comment]
I think the core functionality of the filelist plugin is useful and something people want, but I don't want to build in any special logic to find where the toplevel core file is located.

The closest thing I can give you is to do something like
    DIR=`fusesoc core show <your_core> | grep Core\ root | sed 's/^Core root: *//g'
    fusesoc run <your_core> --outpath=$DIR

which would give you the directory of the top level core file.

If that works for you, I think we can modify the backend to drop the top_core dependency. Otherwise I am fine with removing it for now and put this functionality back at a later point.
