### ISSUE TITLE
Efinix FPGA support

### ISSUE THREAD

**Issue by sebinho** [olofk/edalize#378]
Hi Guys,

Is there any Efinix FPGA support that is planned in the future?

Thanks!

**Comment by olofk** [comment]
Would love to have that and hope that someone will add it.

**Comment by RiceShelley** [comment]
Is there an active branch / anyone working on this? If not I'd like to try adding it.

**Comment by sebinho** [comment]
I made my own implementation that is working well for my use case. I would be willing to share it but knowing that it most likely is not yet production ready and might have to be tuned in order to be put on the main branch.

**Comment by RiceShelley** [comment]
I would love to take a look / help streamline.

**Comment by sebinho** [comment]
I created a pull request that includes my code:
https://github.com/olofk/edalize/pull/395

My fork can be found here:
https://github.com/sebinho/edalize

If you have any questions on how to use it, let me know.
Cheers

**Comment by olofk** [comment]
Thanks for this! I will look at the PR and add comments there.

Also, let the Efinity toolchain serve as an example why you should never ever ask your EDA tool vendors to supply a Python interface for their tools :)

**Comment by olofk** [comment]
Well then. Happy to report we now have an Efinity backend. Thanks for that @sebinho. Will push a Servant port, LED to Believe port and CoreScore as well for my Xyloni board to have some examples
