### ISSUE TITLE
Vivado backend 'file_type=data' type

### ISSUE THREAD

**Issue by djcopley** [olofk/edalize#43]
In the vivado backend source code it says:
```
- IP: Supply the IP core xci file with file_type=xci and other files (like .prj)
      as file_type=data
```
However, this is the only reference to file_type=data that I found. Is this a mistake?

**Comment by olofk** [comment]
Yes, this is a mistake. That should be user instead of data

**Comment by djcopley** [comment]
How does realize treat user files? Does it just copy them to the ../src dir?

**Comment by olofk** [comment]
Yes and no. Technically FuseSoC does the copying and edalize promises to not do anything at all. So the main use is to get files in the build tree without anyone touching them. This is for example used for data files that are read by HDL files or scripts during the build process
