### ISSUE TITLE
Line 7162: Done fix

### ISSUE THREAD

**Issue by emard** [olofk/edalize#58]
This is a fix for common issue for ULX3S.
Include in your bitstream
assign wifi_gpio0 = btn[0]; // btn0 is 0 pressed (exception), other btn's 1-6 are 1 when pressed

what happens without this line is that ESP32 firmware by default looks
for wifi_gpio0 = 0 holding for few seconds and it will JTAG passthru
bitstream to take control over the board.

With above line only if you hold btn0 long, then ESP32 will take control otherwise
your bitstream will keep running normally

**Comment by olofk** [comment]
Thanks. I have improved the ulx3s targets for [project LED to Believe](https://github.com/fusesoc/blinky) to properly handle this
