### ISSUE TITLE
Synthesis only option for Quartus

### ISSUE THREAD

**Issue by a-gibson** [olofk/edalize#63]
I would really like to be able to synthesise my RTL without being forced to do a full P&R. I see this option is available for Vivado as a tool option.

Could we have this option for Quartus as well?

**Comment by a-gibson** [comment]
I have a local branch with proposed changes for this but can't seem to push it. Are there repository restrictions preventing me from creating branches? I can't seem to create branches through the web interface either.

**Comment by olofk** [comment]
Fixed by #66
