### ISSUE TITLE
Provide support for vcom_options

### ISSUE THREAD

**Issue by a-gibson** [olofk/edalize#82]
I need to provide an option to the `vcom` command in ModelSim, specifically `-O0` because ModelSim optimisation is doing bad things to a test bench.

I see that there is support for `vlog_options`, so following convention I guess there should be support for `vcom_options`.

**Comment by olofk** [comment]
Can you try the vcom branch and see if it does the trick?

**Comment by a-gibson** [comment]
That works perfectly, thank you!

**Comment by olofk** [comment]
Great. Thanks for reporting and checking
