### ISSUE TITLE
Support for verible style lint and formatter

### ISSUE THREAD

**Issue by msfschaffner** [olofk/edalize#95]
Just putting down a note here that it would be great if we can eventually add support for Verible, an open-source style linter/formatter (see: https://github.com/google/verible).

I will add some examples of how this tool can be invoked later.

@imphil @fangism for visibility.

**Comment by msfschaffner** [comment]
Simple run scripts for both tool modes can be found in the PR I just linked in above.

**Comment by mithro** [comment]
FYI -- @hzeller @imphil

**Comment by olofk** [comment]
Love to have verible support. Unfortunately I don't have the bandwidth to look into this myself ATM but I'm happy to review any PR that comes up
